name: todoz_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  shared_preferences: ^2.2.3
  uuid: ^3.0.4
  
flutter:
  uses-material-design: true

  assets:
    - assets/create.png
    - assets/done.png
    - assets/dots.png
    - assets/todolist.png
    - assets/trashcan.png
    - assets/notask.png
    - assets/align.png
    - assets/ios_icon.png